# Generated by Django 4.0.2 on 2022-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=200)),
                ('SiteURL', models.CharField(max_length=1000)),
                ('AboutSite', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('emailId', models.CharField(max_length=200)),
            ],
        ),
    ]
