# Generated by Django 4.0.2 on 2022-02-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
