# Generated by Django 4.0.2 on 2022-02-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
