# Generated by Django 4.0.2 on 2022-02-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0015_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='topic',
        ),
    ]
