# Generated by Django 4.0.2 on 2022-02-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0016_rename_category_product_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eapp.topic'),
        ),
    ]
