# Generated by Django 4.0.2 on 2022-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0017_alter_product_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
