# Generated by Django 4.0.2 on 2022-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0018_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimg',
            field=models.ImageField(null=True, upload_to='eapp/images'),
        ),
    ]
