# Generated by Django 4.0.2 on 2022-02-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0019_alter_product_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productimg',
        ),
    ]
