# Generated by Django 4.0.2 on 2022-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0020_remove_product_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='eapp/images'),
        ),
    ]
