# Generated by Django 4.0.2 on 2022-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0022_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
