# Generated by Django 4.0.2 on 2022-02-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0025_addcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='filepath'),
        ),
        migrations.DeleteModel(
            name='AddCat',
        ),
    ]
