# Generated by Django 4.0.2 on 2022-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0028_product_digital_product_topic_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank='', default='', null=True),
        ),
    ]
