# Generated by Django 4.0.2 on 2022-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0029_alter_product_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
