# Generated by Django 4.0.2 on 2022-02-22 09:01

from django.db import migrations, models
import eapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0030_alter_product_digital_alter_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to=eapp.models.filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', upload_to=eapp.models.filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', upload_to=eapp.models.filepath),
        ),
    ]
